### PR TITLE
Change kotlin-eap repository urls to https

### PR DESCRIPTION
**Pull request by hanleyt**
Hey @objcode,

Just ran this codelab with the Dublin Kotlin User Group, thanks so much!

Some people had some issues due to the kotlin-eap repository url being http instead of https so said I'd open a PR.

Thanks,
Tomás

### CODE REVIEW

**Comment by hanleyt** [comment]
> I signed it!

**Comment by objcode** [comment]
Thanks for the PR!

How did the codelab go at the meetup?

**Comment by tomashanley-toast** [comment]
The codelab went really well! People seemed to get a lot out of it and I'm super excited to bring coroutines into my company!

I'm trying to remember, did you say that coroutines are due to become googles recommended way to do async on Android?

**Comment by LouisCAD** [comment]
Why would you need Google recommendation to use one of Kotlin's best
features?
I've been using coroutines for a year, and of course, they'll recommend
using it if you ask me (they are sort of already doing it).

**Comment by tomashanley-toast** [comment]
Theres some questions over RxJava vs coroutines that I was hoping i could settle easily with a recommendation from Google!
I personally love coroutines and am already using them, I'm just trying to figure out ways to convince the rest of my company :)

**Comment by objcode** [comment]
Coroutines is going to be something we'll be promoting for use in Android development, but we're also happy with apps using Rx too!

**Comment by tomashanley-toast** [comment]
Ok good to know, thanks Sean!

**Pull request merged**
